# Use an official Node.js runtime as a parent image
FROM node:22-alpine as dev

# ติดตั้ง curl เพื่อให้สามารถทดสอบ API ได้
RUN apk add --no-cache curl

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies 
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Build the application
CMD ["npm", "run", "dev", "--", "--host"]

# Expose the port the app runs on
EXPOSE 5173

