version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb_service
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    container_name: Server-Api
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_HOST=redis_service
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongodb_service:27017/modmark

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    container_name: Client-App
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
    - VITE_API_URL=http://Server-Api:5001

volumes:
  mongo_data: