# Development stage
FROM node:22-alpine as dev

# Define working directory in container
WORKDIR /app

# Copy package.json and package-lock.json to container
COPY package*.json ./
RUN npm install && npm install -g nodemon dotenv

# Copy all files to container
COPY . .

CMD ["sh", "-c", "sleep 5 && npm run dev"]

EXPOSE 5001
